index.html

bugfix: исправлено название проекта

---

pages/index.css
vendor/normalize.css

feat: Подключение normalize.css

---

blocks/page/page.css
index.html
pages/index.css

add style font

---

blocks/content/content.css
index.html
pages/index.css

added "content" block

---

blocks/header/__link/header__link.css

feat: Подключение стилей блока Header + правка_2

---

index.html

Добавлен блок sidebar в блок main

сверстан компонент sidebar

---

blocks/sidebar/__under-item/sidebar__under-item.css
blocks/sidebar/__under-list/_visible/sidebar__under-list_visible.css
blocks/sidebar/__under-list/sidebar__under-list.css

- убрал margin-top 
- добавил при появлении

refact: изменение отступов, как в макете

---

scripts/index.js

Добавляется класс sidebar__order-icon_active при нажатии на элемент sidebar

refact: Добавление активности всем стрелкам блока sidebar

---

blocks/content/content.css
index.html

Добавлен нижний отступ от экрана + небольшие правки

fixbugs: добавлен нижний отступ блока content + небольшие правки

---

blocks/button/__arrow/_forward-grey/button__arrow_forward-grey.css
blocks/button/__arrow/_forward-white/button__arrow_forward-white.css
blocks/button/button.css
blocks/buttons/buttons.css
index.html

Блок с кнопками + медиа + небольшие правки в стилях кнопок

style: оформлен блок с кнопками

---

blocks/range/range.css
blocks/sidebar/sidebar.css
blocks/video/__controls/video__controls.css
blocks/video/__fullscreen/video__fullscreen.css
blocks/video/__loading/video__loading.css
blocks/video/__play-btn/video__play-btn.css
blocks/video/__sound-block/video__sound-block.css
blocks/video/__sound-btn/video__sound-btn.css
blocks/video/__sound-regulation/video__sound-regulation.css
blocks/video/video.css
contentVideo.html
pages/contentVideo.css
scripts/index.js

- Адаптив
- JavaScript для ползунков

feat: создан блок видео

---

blocks/content-block/content-block.css
contentVideo.html
index.html
pages/index.css

fixbugs: правка разметки и стилей

---

blocks/content-block/__content/content-block__content.css
blocks/content-block/__header/content-block__header.css
blocks/content-block/__result/content-block__result.css
blocks/sidebar/sidebar.css
blocks/video/video.css
content-course-completed-loss/index.css
content-course-completed-loss/index.html
content-course-completed-win/index.css
content-course-completed-win/index.html
contentVideo.html
pages/contentVideo.css
pages/index.css

Правки для для блоков sidebar, video, content-block

fixbugs: блок content, sidebar, video + style

---

blocks/form/__checkbox/form__checkbox.css
blocks/form/__input/form__input.css
blocks/form/__label/form__label.css
blocks/form/__pseudo-item/form__pseudo-item.css
blocks/form/__pseudo-text/form__pseudo-text.css
blocks/form/__radio/form__radio.css
blocks/form/form.css
pages/index.css
scripts/testInwork.js
testInwork.html

added testInwork page

---

blocks/content-block/__result-title/content-block__result-title.css
blocks/content-block/__resutl-text/content-block__result-text.css
pages/testCompleetLoss.css
pages/testCompleetWin.css
testCompleetWin.html
testCompletedLoss.html

Рефакторинг наименования классов для блока content-block__result

refactor: изменены название классов текста для блока result

---

pages/contentVideo.css

style: добавил комментарии

---

blocks/content-block/__button-header/content-block__button-header.css
blocks/content-block/__header/content-block__header.css
pages/testAbout.css
testAbout.html

add page testAbout

---

blocks/content-block/__content/content-block__content.css
blocks/content-block/__header/content-block__header.css
blocks/content-block/__result-title/content-block__result-title.css
blocks/content-block/__result/content-block__result.css
blocks/content-block/__resutl-text/content-block__result-text.css
blocks/content-block/__text-bold/content-block__text-bold.css
blocks/content-block/__text/content-block__text.css
pages/testInWork.css
testInwork.html

fixbugs: return styles content-block

---

blocks/content-block/__button/content-block__button.css
blocks/form/__icon/_fail-active/form__icon_fail-active.css
blocks/form/__icon/_fail/form__icon_fail.css
blocks/form/__icon/_right-active/form__icon_right-active.css
blocks/form/__icon/_right/form__icon_right.css
blocks/form/__input/form__input.css
blocks/form/__label/_cursor-non/form__label_cursor-non.css
blocks/form/__label/form__label.css
blocks/form/__pseudo-item/form__pseudo-item.css
blocks/form/__pseudo-text/_fail/form__pseudo-text_fail.css
blocks/form/__pseudo-text/_right/form__pseudo-text_right.css
blocks/form/form.css
blocks/result/result.css
pages/testResultLoss.css
pages/testResultWin.css
testResultLoss.html
testResultWin.html

feat: add testResult win and loss HTMl

---

blocks/breadcrumbs/__item/breadcrumbs__item.css
blocks/breadcrumbs/__text/breadcrumbs__text.css
blocks/page/page.css

У нас каждый элемент был цвета var(--black), сейчас исправлено:)

bugfix: исправил текст на блоке breadcrumbs

---

blocks/content-block/__about/content-block__about.css
testAbout.html
testPreview.html

Второй раз заливаю изменения страниц testAbout и testPreview

fix page about & preview
